namespace EndPointConnector.Models
{
    public static class ArtefactType
    {
        public enum ArtefactEnumType
        {
            Null = 0,
            Any = 1,
            Annotation = 2,
            CategoryId = 3,
            Datasource = 4,
            TextFormat = 5,
            TextType = 6,
            RelatedStructures = 7,
            CodeListRef = 8,
            Contact = 9,
            Component = 10,
            Dataset = 11,
            DatasetReference = 12,
            ItemMap = 13,
            LocalRepresentation = 14,
            Computation = 15,
            InputOutput = 16,
            ConstrainedDataKey = 17,
            ConstrainedDataKeyset = 18,
            AttachmentConstraintAttachment = 19,
            ContentConstraintAttachment = 20,
            ReferencePeriod = 21,
            ReleaseCalendar = 22,
            TimeRange = 23,
            KeyValues = 24,
            CubeRegion = 25,
            Constraint = 26,
            MetadataDocument = 27,
            MetadataSet = 28,
            MetadataReport = 29,
            MetadataReportTarget = 30,
            MetadataReferenceValue = 31,
            MetadataReportAttribute = 32,
            AgencyScheme = 33,
            Agency = 34,
            DataProviderScheme = 35,
            DataProvider = 36,
            DataConsumerScheme = 37,
            DataConsumer = 38,
            OrganisationUnitScheme = 39,
            OrganisationUnit = 40,
            CodeList = 41,
            Code = 42,
            HierarchicalCodelist = 43,
            Hierarchy = 44,
            HierarchicalCode = 45,
            Level = 46,
            Categorisation = 47,
            CategoryScheme = 48,
            Category = 49,
            ReportingTaxonomy = 50,
            ReportingCategory = 51,
            ConceptScheme = 52,
            Concept = 53,
            Dsd = 54,
            DataAttribute = 55,
            AttributeDescriptor = 56,
            Dataflow = 57,
            Dimension = 58,
            Group = 59,
            CrossSectionalMeasure = 60,
            DimensionDescriptor = 61,
            MeasureDimension = 62,
            MeasureDescriptor = 63,
            PrimaryMeasure = 64,
            TimeDimension = 65,
            Msd = 66,
            ReportStructure = 67,
            MetadataAttribute = 68,
            MetadataTarget = 69,
            MetadataFlow = 70,
            IdentifiableObjectTarget = 71,
            DatasetTarget = 72,
            ConstraintContentTarget = 73,
            DimensionDescriptorValuesTarget = 74,
            ReportPeriodTarget = 75,
            Process = 76,
            ProcessStep = 77,
            Transition = 78,
            ProvisionAgreement = 79,
            Registration = 80,
            Subscription = 81,
            AttachmentConstraint = 82,
            ContentConstraint = 83,
            StructureSet = 84,
            StructureMap = 85,
            ReportingTaxonomyMap = 86,
            RepresentationMap = 87,
            CategoryMap = 88,
            CategorySchemeMap = 89,
            ConceptSchemeMap = 90,
            CodeMap = 91,
            CodeListMap = 92,
            ComponentMap = 93,
            ConceptMap = 94,
            OrganisationMap = 95,
            OrganisationSchemeMap = 96,
            HybridCodelistMap = 97,
            HybridCode = 98,
            MetadataTargetRegion = 99,
            Organisation = 100,
            OrganisationScheme = 101,
            AllowedConstraint = 102,
            ActualConstraint = 103
        }

        public enum ReferenceDetailEnumType
        {
            Null = 0,
            None = 1,
            Parents = 2,
            ParentsSiblings = 3,
            Children = 4,
            Descendants = 5,
            All = 6,
            Specific = 7
        }

        public enum ResponseDetailEnumType
        {
            Stub,
            Full,
            None,
            Null,
            CompleteStub,
            ReferencePartial
        }
    }
}