// <auto-generated />
using System;
using DataBrowser.DB.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBrowser.DB.EFCore.Migrations.DataBrowserUpdater
{
    [DbContext(typeof(DataBrowserUpdaterContext))]
    [Migration("20201008041132_UpdaterTable")]
    partial class UpdaterTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("DataBrowser.Domain.Entities.Versioning.DataBrowserVersion", b =>
                {
                    b.Property<int>("DataBrowserVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Build")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("DataBrowserVersionId");

                    b.ToTable("DataBrowserVersion");
                });

            modelBuilder.Entity("DataBrowser.Domain.Entities.Versioning.DataBrowserVersionActionUpgrader", b =>
                {
                    b.Property<int>("DataBrowserVersionActionUpgraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataBrowserVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("DataBrowserVersionActionUpgraderId");

                    b.ToTable("VersionActions");
                });
#pragma warning restore 612, 618
        }
    }
}
